[build-system]
requires = ["setuptools","wheel"]
build-backend= "setuptools.build_meta"

[project]
name = "module-network-pentest-kalia"
version = "0.1.0"
description = "Independent network module extracted from Kalia"
authors = [{ name = "St√©phane Kamwa"}]
dependencies = []