name: Deploy UI

on:
  push:
    branches: ["main"]
    paths:
      - "ui/**"
      - ".github/workflows/ui.yml"

jobs:
  flutter-web-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Build UI Docker image
        run: |
          docker build -t mydocker/kalia-ui:latest -f ui/Dockerfile.ui .

      - name: Push UI Docker image
        run: docker push mydocker/kalia-ui:latest

      - name: Deploy UI to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "kalia-ui"
          images: "mydocker/kalia-ui:latest"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
