name: Deploy Flutter Web to Azure Static Web Apps

on:
  push:
    branches:
      - main
    paths:
      - "PentestingUI/**"
      - ".github/workflows/azure-static-web-apps.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        working-directory: PentestingUI
        run: flutter pub get

      - name: Build Flutter web
        working-directory: PentestingUI
        run: flutter build web --release

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GRASS_0F7FA851E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "PentestingUI"
          output_location: "PentestingUI/build/web"
